### ISSUE TITLE
Reference Input 1 in Input 2 in a task

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/wdl4s#20]
The following wdl doesn't run in Cromwell:

```
task t {
    String my_input_string
    String other_string = my_input_string + " bla"

    command {
      echo ${other_string}
    }
}

workflow w {
 call t {input: my_input_string = "bla"}
}
```

**Comment by cjllanwarne** [comment]
NB: Only happens if the referenced input comes from outside. i.e. this would be fine:
```
task t {
  String my_input_string = "bla"
  String other_string = my_input_string + " blah"
  ...
}
```

**Comment by scottfrazer** [comment]
The description might be misleading: the WDL does parse and is semantically correct.  It's really just a bug in Cromwell, but the solution to this bug can (and probably should) be pushed into wdl4s from Cromwell.  The `recursive_interpolation` branch of wdl4s has the ability to generate a lookup function that will appropriately take into account the `input: ` section of `call`s.  If we use this instead of Cromwell's custom lookup, we can get rid of code in Cromwell and make it generic to any consumer of wdl4s

**Comment by Horneth** [comment]
Hmm right, maybe I should close this issue and re-open it in Cromwell then ?

**Comment by scottfrazer** [comment]
The change that I propose to fix this is to give all `Scope`s a new method

```
def lookupFunction(...): String => WdlValue
```

Where the parameters to the lookup function give it enough information to do scope resolution and implement other subtleties like take into account  the `input: ` section of a `call`.

This way, anytime you're evaluating an expression, you acquire an appropriate lookup function from the `Scope` itself.

**Comment by scottfrazer** [comment]
I think it belongs here, but Cromwell will have to change too

**Comment by cjllanwarne** [comment]
Closing as working
